service: wateratlas
runtime: python39
instance_class: F4

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

#entrypoint: gunicorn -b :8080 -w 2 main:app
- url: .*
  script: main.app

#libraries:
#- name: webapp2
#  version: "2.5.2"
